- hosts: all
  become: true
  pre_tasks:
    
    - name: MOTD
      copy:
          content: "Ansible Managed by Baltazar"
          dest: /etc/motd

- hosts: all
  become: true
  roles:
    - Prometheus
    - apache2
