---

  - name: Install apache and php (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php (CentOS)
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
