---

  - name: Prometheus Install (Ubuntu)
    apt:
      name: prometheus
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: snapd install (CentOS)
    yum:
      name:
        - snapd
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Enabling Sockets (CentOS)
    command: systemctl enable --now snapd.socket
    when: ansible_distribution == "CentOS"

  - name: Prometheus Install (CentOS)
    command: snap install prometheus --classic
    when: ansible_distribution == "CentOS"
